### ISSUE TITLE
Your demo cannot be displayed

### ISSUE THREAD

**Issue by playertk** [guyettinger/gle-scene-components#1]
I want to see how your components are used, but your demo website seems to be experiencing issues, and I am unable to see the correct call code example. It always shows loading
[demo](https://gle-scene-components.vercel.app/?path=/story/gle-scene-components-scene--gaussian-splat-clouds)

**Comment by guyettinger** [comment]
Thanks for contacting me @playertk! I'm seeing the same issue on vercel, but not locally.  Digging into it ... I'll let you know when I've found a solution.

**Comment by guyettinger** [comment]
@playertk - this should be resolved.  Thanks for letting me know!
